
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

CREATE TABLE Accounts (Login VARCHAR(20) PRIMARY KEY, SecretPass TEXT NOT NULL, Status TEXT NOT NULL);
CREATE TABLE AccountsRole (AccRoleID INTEGER AUTO_INCREMENT PRIMARY KEY, Login TEXT REFERENCES Accounts (Login), RoleID TEXT NOT NULL);
CREATE TABLE Classes (ClassID INTEGER AUTO_INCREMENT PRIMARY KEY, ClassTitle TEXT NOT NULL);
CREATE TABLE ClassesInSchools (CISID INTEGER AUTO_INCREMENT PRIMARY KEY, SchoolID INTEGER REFERENCES Schools (SchoolID), ClassID INTEGER REFERENCES Classes (ClassID));
CREATE TABLE ClassInvitations (
    InvitationID INTEGER AUTO_INCREMENT PRIMARY KEY,
    ClassID INTEGER REFERENCES Classes (ClassID),
    StudentID INTEGER REFERENCES Students (StudentID),
    TeacherID INTEGER REFERENCES Teachers (TeacherID),
    Status TEXT NOT NULL, -- 'pending', 'accepted', 'rejected'
    CreatedAt INTEGER NOT NULL,
    UpdatedAt INTEGER);

CREATE TABLE MyClasses (MCID INTEGER AUTO_INCREMENT PRIMARY KEY, ClassID INTEGER REFERENCES Classes (ClassID), TeacherID INTEGER REFERENCES Teachers (TeacherID));
CREATE TABLE Schools (SchoolID INTEGER AUTO_INCREMENT PRIMARY KEY, SchoolName TEXT NOT NULL, SchoolCode TEXT NOT NULL);
CREATE TABLE SolutionFiles (
    FileID INTEGER AUTO_INCREMENT PRIMARY KEY,
    STID INTEGER REFERENCES StudentTasks (STID),
    FileName TEXT NOT NULL,
    FileData BLOB NOT NULL,
    MimeType TEXT NOT NULL
);

CREATE TABLE StudentInClasses (SICID INTEGER AUTO_INCREMENT PRIMARY KEY, ClassID INTEGER REFERENCES Classes (ClassID), StudentID INTEGER REFERENCES Students (StudentID));
CREATE TABLE Students (StudentID INTEGER AUTO_INCREMENT PRIMARY KEY, Login TEXT REFERENCES Accounts (Login), LastName TEXT NOT NULL, FirstName TEXT NOT NULL, MiddleName TEXT NOT NULL);
CREATE TABLE StudentTasks (STID INTEGER AUTO_INCREMENT PRIMARY KEY, StudentID INTEGER REFERENCES Students (StudentID), TaskID INTEGER REFERENCES Tasks (TaskID), Decision TEXT, Mark TEXT, Comment TEXT, Status TEXT NOT NULL, DispatchDT INTEGER);

CREATE TABLE Subjects (SubjectID INTEGER AUTO_INCREMENT PRIMARY KEY, SubjectTitle VARCHAR(255) NOT NULL UNIQUE);
CREATE TABLE TaskFiles (
    FileID INTEGER AUTO_INCREMENT PRIMARY KEY,
    TaskID INTEGER REFERENCES Tasks (TaskID),
    FileName TEXT NOT NULL,
    FileData BLOB NOT NULL,
    MimeType TEXT NOT NULL
);

CREATE TABLE Tasks (TaskID INTEGER AUTO_INCREMENT PRIMARY KEY, Date INTEGER NOT NULL, ClassID INTEGER REFERENCES Classes (ClassID), TeacherID INTEGER REFERENCES Teachers (TeacherID), SubjectID INTEGER REFERENCES Subjects (SubjectID), Topic TEXT NOT NULL, Text TEXT NOT NULL);

CREATE TABLE Teachers (TeacherID INTEGER AUTO_INCREMENT PRIMARY KEY, Login TEXT REFERENCES Accounts (Login), LastName TEXT NOT NULL, FirstName TEXT NOT NULL, MiddleName TEXT NOT NULL);
CREATE TABLE TeachersInSchools (TISID INTEGER AUTO_INCREMENT PRIMARY KEY, SchoolID INTEGER REFERENCES Schools (SchoolID), TeacherID INTEGER REFERENCES Teachers (TeacherID));

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
